# Generated by Django 2.2.3 on 2019-07-11 19:11

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='pdf-base/')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='F:\\Projects\\django_pdf\\fillable\\pdf-base'), upload_to='')),
                ('inserted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDF',
                'verbose_name_plural': 'PDFs',
            },
        ),
        migrations.CreateModel(
            name='PDFPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='forms.PDF')),
            ],
            options={
                'unique_together': {('pdf', 'number')},
            },
        ),
        migrations.CreateModel(
            name='PDFField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('x', models.IntegerField(default=10)),
                ('y', models.IntegerField(default=10)),
                ('default', models.CharField(blank=True, max_length=255)),
                ('system_info', models.CharField(blank=True, max_length=255)),
                ('obj_name', models.CharField(blank=True, max_length=255)),
                ('font_size', models.IntegerField(default=12)),
                ('font_color', models.CharField(default='black', max_length=50)),
                ('font', models.CharField(default='Helvetica', max_length=50)),
                ('inserted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('system_default_x', models.IntegerField(default=10)),
                ('system_default_y', models.IntegerField(default=10)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.PDFPage')),
            ],
            options={
                'unique_together': {('page', 'name')},
            },
        ),
    ]
