# Generated by Django 2.2.3 on 2019-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='image',
        ),
        migrations.AddField(
            model_name='pdfpage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='pdf-base/'),
        ),
    ]
